import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useListSlotsQuery } from "../api/queries/slots";
import { formatTimestamp } from "../helpers/TimeHelpers";

export default function Home() {
  const { data } = useListSlotsQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Rezerwacje na kroplówki witaminowe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Dostępne terminy</h1>
      {data?.slots.map((slot) => (
        <li key={slot.id}>
          {formatTimestamp(slot.startTime)}&ndash;
          {formatTimestamp(slot.endTime)}
        </li>
      ))}
    </div>
  );
}
